export const en = {
  common: {
    language: "Language", systemDefault: "System default", english: "English", spanish: "Spanish", french: "French",
    loading: "Loading…", cancel: "Cancel", close: "Close", save: "Save", remove: "Remove", retry: "Retry", refresh: "Refresh",
    enabled: "Enabled", disabled: "Disabled", yes: "Yes", no: "No", photos: "{{count}} photo", photos_other: "{{count}} photos",
    files: "{{count}} file", files_other: "{{count}} files", previous: "Previous", next: "Next", search: "Search", continue: "Continue", ok: "OK", yearsAgo: "{{count}} year ago", yearsAgo_other: "{{count}} years ago", all: "All", photosOnly: "Photos only", videosOnly: "Videos only", filterMedia: "Filter by media type",
    play: "Play", pause: "Pause", add: "Add", cover: "Cover", openPhoto: "Open photo", confirmedByYou: "Confirmed by you", confirm: "Confirm", yesThem: "Yes, it's them", notThem: "Not them", notThisPerson: "Not this person",
    slideshowLabel: "Photo slideshow, currently showing {{filename}}. Use left and right arrow keys to navigate, space to play or pause.", openFile: "Open {{filename}}", stackExpand: "Stack of {{count}} — click to expand", stackLabel: "Stack of {{count}}",
    tags: "Tags", addTag: "Add a tag", removeTag: "Remove {{name}} tag", addTagFailed: "Could not add tag", removeTagFailed: "Could not remove tag",
    pageLoadTitle: "Approximate initial load: API requests and visible images. Excludes later polling, slideshow changes and offscreen images.", pageLoading: "Page loading…", pageLoaded: "Page loaded in {{seconds}} s",
    applePreview: "Original is in iCloud — showing Apple's preview.", openPhotos: "Open in Photos", originalUnavailable: "Original unavailable", cachedThumbnail: "showing cached thumbnail. Reconnect the drive or scan folder to view full resolution.",
  },
  navigation: {
    browse: "Browse", favorites: "Favorites", people: "People", library: "Library", locations: "Locations", tags: "Tags",
    reports: "Reports", gearMuseum: "Gear Museum", gearTimeline: "Gear Timeline", cleanup: "Cleanup", settings: "Settings",
    search: "Search", logout: "Log out", libraryPages: "Library pages", signedInSettings: "Signed in — go to Settings to change your password",
  },
  auth: {
    signIn: "Sign in", username: "Username", password: "Password", currentPassword: "Current password", newPassword: "New password",
    loginFailed: "Login failed", setupTitle: "Set up MemoryLane", setupIntro: "Create the administrator account for this archive.",
    createAccount: "Create account", creating: "Creating…", signingIn: "Signing in…", confirmPassword: "Confirm password",
    passwordsMismatch: "Passwords do not match", changePassword: "Change password", passwordChanged: "Password changed.",
    intro: "Reconnect with the memories already sitting in your photo archive.", welcome: "Welcome to MemoryLane", setupAccount: "Let's create your admin account.", setupFailed: "Setup failed",
  },
  settings: {
    title: "Settings", folders: "Folders & Exclusions", analysis: "AI & Analysis", plugins: "Plugins", storage: "Storage",
    network: "Network", account: "Account", about: "About", theme: "Theme", museumTitle: "MemoryLane Museum Service",
    museumIntro: "Control the optional museum service used to enrich gear information.", museumEnable: "Enable MemoryLane Museum Service",
    museumHelp: "Disabled by default. Enable it to retrieve optional camera and lens enrichment from the Museum Service.", networkIntro: "Control where MemoryLane can be reached. Network changes take effect after MemoryLane is restarted.",
    allowRemote: "Allow Access outside this computer", allowRemoteHelp: "Off by default, so MemoryLane is available only on this computer. Restart MemoryLane to apply this change.",
    signedInAs: "Signed in as {{username}}", appearance: "Appearance",
    sections: "Settings sections", scanFolders: "Scan Folders", ignoredFolders: "Ignored Folders", removeIgnored: "Remove from ignore list", scanning: "Scanning", runningAnalysis: "Running Analysis", people: "People", stacks: "Stacks", accountHeading: "Account",
  },
  viewer: {
    close: "Close viewer", previous: "Previous photo", next: "Next photo", favorite: "Add to favorites", unfavorite: "Remove from favorites",
    camera: "Camera", lens: "Lens", focalLength: "Focal length: {{value}} mm", dimensions: "Dimensions: {{width}} × {{height}}",
    type: "Type: {{type}}", file: "File", folder: "Folder", similar: "Find similar", fullscreen: "Full screen", exitFullscreen: "Exit full screen",
    apertureTitle: "See every photo at this aperture", focalTitle: "See every photo at this focal length", lensTitle: "See every photo with this lens", cameraTitle: "See every photo with this camera",
    playLive: "Play Live Photo", openRaw: "Open original RAW file", zoomOut: "Zoom out", zoomIn: "Zoom in", closeInfo: "Close info", info: "Info", isoTitle: "See every photo at this ISO",
  },
  pages: {
    favorites: "Favorites", noFavorites: "No favorites yet — star a photo from the viewer or from a folder grid to see it here.",
    people: "People", locations: "Locations", tags: "Tags", reports: "Reports", cleanup: "Cleanup", search: "Search",
    surprise: "Surprise Me", similar: "Similar Photos", loadingMap: "Loading map…", noResults: "No results found.", gathering: "Gathering memories…", noIndexed: "No indexed photos yet — add a scan folder and run a scan from Settings first.",
    searchMode: "Search mode", names: "Names", describeAi: "Describe it (AI)", textSearchPlaceholder: "Search folders, filenames, camera, lens…", aiSearchPlaceholder: "a bird taking off from water, a red car at night, snow on mountains…", searchFailed: "Search failed", folders: "Folders", photosVideos: "Photos & Videos", yourLibrary: "Your Library", cameras: "Cameras", lenses: "Lenses",
  },
  analysisProgress: {
    exif: "EXIF metadata", fingerprints: "Visual fingerprints (stacks)", embeddings: "AI embeddings (similar, search, stacks)", aiTags: "AI photo tags", imported: "Imported keywords", faces: "Faces (People)",
    off: "Off", waiting: "Waiting for sidecar", paused: "Paused during scan", failing: "Failing", working: "Working", retry: "Needs retry", done: "Done",
    underMinute: "under a minute", aboutMinutes: "about {{count}} min", aboutHours: "about {{value}} h", nothing: "Nothing to analyse yet.", scanPaused: "A scan is running — analysis resumes when it finishes.", left: "{{eta}} left", failed: "{{count}} file failed", failed_other: "{{count}} files failed", peopleOff: "Turn on People below to start finding faces.", aiOff: "AI analysis is switched off above.", lastError: "last error:", fixRetry: "Fix the cause, then use Retry failed under Settings › Analysis.",
  },
  scanning: {
    noMedia: "No media indexed yet", photos: "{{count}} photo", photos_other: "{{count}} photos", videos: "{{count}} video", videos_other: "{{count}} videos", folders: "{{count}} folder", folders_other: "{{count}} folders", pending: "{{count}} pending", failed: "{{count}} failed",
    progress: "{{scanned}} files scanned, {{newCount}} new, {{errors}} errors so far.", generating: "Generating thumbnails:", thumbnailsDone: "Thumbnails done:", of: "{{current}} of {{total}}", addFailed: "Could not add folder", scanFailed: "Could not start scan",
    removeTitle: "Remove this folder from MemoryLane?", removeMessage: "{{path}} is removed from the library. Original files are never touched — this only removes MemoryLane's index for the folder.", removeFolder: "Remove folder", pathPlaceholder: "e.g. D:\\Photos or /mnt/photos", addFolder: "Add Folder",
    orderHelp: "Order here also sets the order folders appear in on the Home page.", moveUp: "Move up", moveDown: "Move down", enableToScan: "Enable this folder to scan it", scanning: "Scanning…", scanNow: "Scan Now", enable: "Enable", disable: "Disable", remove: "Remove", modernize: "{{count}} video could be modernized →", modernize_other: "{{count}} videos could be modernized →", none: "No folders added yet.",
  },
  stacks: {
    title: "Stack", titleDetail: "Stack · {{count}} photos · {{kind}}", view: "View", setCover: "Set as cover", setCoverHelp: "Use the selected photo as this stack's cover", split: "Split into new stack", splitHelp: "Move the selected photos into their own stack", remove: "Remove from stack", removeHelp: "Remove the selected photos from this stack (they won't be auto-stacked again)",
    deleteTitle: "Delete this stack?", deleteMessage: "The photos stay in your library — they just won't be grouped, and won't be auto-stacked again.", delete: "Delete stack", selectHelp: "Click photos to select them.", selected: "{{count}} selected.", edited: "Edited by you — automatic re-stacking leaves this stack alone.", automatic: "Grouped automatically.", error: "Something went wrong",
  },
  pluginUi: {
    loadFailed: "Could not load plugins", genericError: "Something went wrong.", installing: "Installing {{name}}…", updating: "Updating {{name}}…", changeFailed: "Could not change {{name}}", removeTitle: "Remove {{name}}?", removeMessage: "The plugin can be downloaded again later. Indexed core data is preserved.", removePlugin: "Remove plugin", removed: "Plugin removed", removedMessage: "{{name}} was removed.", removeFailed: "Could not remove {{name}}",
    required: "Required", optional: "Optional", requires: "Requires {{dependencies}}", logs: "Logs", logsUnavailable: "Logs unavailable", install: "Install", update: "Update", disable: "Disable", enable: "Enable", remove: "Remove", updateIntro: "Core and plugin updates are checked daily. Plugin updates roll back when startup health checks fail.", checkUpdates: "Check for updates", updateFailed: "Update check failed",
    core: "Core", builtInRunning: "Built in · v{{version}} · running", installed: "Installed", installedHelp: "Required components plus any optional features you've added.", available: "Available to install", availableHelp: "Install only the features you want.", nothingAvailable: "Nothing else available for this platform right now.", recentOutput: "Recent plugin output", noOutput: "No output recorded.", history: "Update history",
  },
  onboarding: { step1: "MemoryLane setup · Step 1 of 2", welcome: "Welcome to MemoryLane", intro: "The fastest way to resurface old photos and videos and see everything you have in one place — all on your own machine, over your own files. Nothing is uploaded anywhere.", addFolders: "Add your photo folders", foldersHelp: "Point MemoryLane at the folders where your photos and videos already live. It only reads them — nothing is modified, renamed, or moved. You can change these later from Settings or skip this for now.", step2: "MemoryLane setup · Step 2 of 2", optional: "Optional features", optionalHelp: "Install any of these now, or skip and add them later from Settings → Plugins.", storage: "Browser storage estimate: {{storage}}", feature: "Feature component", alsoInstalls: "Also installs: {{dependencies}}", licenses: "Includes first-party software and bundled dependency license notices.", none: "Nothing available to install right now — close to finish setup.", preparing: "Preparing plugins…", installing: "Installing…" },
  updates: { available: "MemoryLane {{version}} is available.", downloading: "Downloading securely…", restart: "Restart to finish the update.", install: "Restart and install", starting: "Starting…", dismiss: "Dismiss update {{version}}" },
  onboardingRuntime: { starting: "Starting {{name}}…", installFailed: "Plugin installation failed" },
  applePhotos: { imageNotLocal: "Image not local", checkLocal: "Check for local copy", title: "Apple Photos", devicePhotos: "Apple Device Photos", unavailablePlatform: "Unavailable on this platform", readOnly: "Read-only import from a local macOS Photos library.", notSynced: "Not synced", preparing: "Preparing Photos catalog{{elapsed}}", elapsed: " · {{seconds}}s elapsed", syncSummary: "{{processed}} / {{total}} · {{status}}", skipped: " · {{count}} skipped", service: "Plugin service: {{status}}. MemoryLane starts and monitors it automatically.", checking: "Checking…", permissionHint: "If the library cannot be read, grant Full Disk Access to MemoryLane in System Settings, then retry.", path: "Photos library path", addLibrary: "Add library", detected: "Detected: {{path}}", usePath: "Use this path", fullDiskAccess: "MemoryLane needs Full Disk Access to read this Photos library. Open System Settings → Privacy & Security → Full Disk Access, enable MemoryLane, then fully quit and reopen MemoryLane.", noLibraries: "No Photos libraries added yet.", indexed: "{{count}} indexed · {{summary}}", availability: "{{previewOnly}} preview-only · {{unavailable}} unavailable", previousError: "Previous sync error: {{error}}", syncNow: "Sync now" },
  appleBrowse: { loadFailed: "Could not load Apple Photos", openFailed: "Could not open Photos", noLocal: "No usable local image yet. View the photo in Photos, then try again.", checkFailed: "Could not check local copy", moreFailed: "Could not load more photos", markTitle: "Mark {{count}} Apple Photos item?", markTitle_other: "Mark {{count}} Apple Photos items?", markMessage: "They will disappear from MemoryLane browsing and remain in Cleanup. No Photos library files will be changed.", mark: "Mark for deletion", markFailed: "Could not mark Apple Photos items", breadcrumbs: "Apple Photos breadcrumbs", allPhotos: "All Photos", unknownDate: "Unknown Date", items: "{{count}} item", items_other: "{{count}} items", select: "Select", selected: "{{count}} selected", selectShown: "Select all {{count}} shown", none: "None", invert: "Invert shown", loadMore: "Load more", loading: "Loading Apple Photos…" },
  appleErrors: { notRunning: "not running", addFailed: "Could not add library", syncFailed: "Could not start sync" },
  settingsUi: {
    theme: { light: "Light", dark: "Dark", dusk: "Dusk", gallery: "Gallery" }, passwordMismatch: "New passwords don't match", passwordFailed: "Could not change password", newPasswordHint: "New password (min. 8 characters)", confirmNewPassword: "Confirm new password", passwordChanged: "Password changed. You'll stay signed in here; any other signed-in devices have been signed out.", changing: "Changing…",
    moveTitle: "Move MemoryLane's data?", moveMessageBefore: "Everything (database, thumbnails, previews, vectors, face crops) is copied to", moveMessageAfter: "now — about a minute per GB, and MemoryLane keeps working meanwhile. Afterwards, restart it to use the new location; the old copy stays until you delete it.", copyData: "Copy data", moveFailed: "Move failed", recomputed: "Recomputed stacks in {{count}} folder.", recomputed_other: "Recomputed stacks in {{count}} folders.", storageFailed: "Could not load storage usage",
    scanFoldersHelp: "Add folders containing your photos and videos. MemoryLane never modifies, renames, or moves originals.", ignoredHelp: "Folders MemoryLane skips during every scan — click “Ignore folder” while browsing a folder to add it here. Removing one from this list doesn't restore anything; it will be picked up fresh on the next scan.", noIgnored: "No ignored folders.", scanEvery: "Scan automatically every", days: "days", scanRunning: "Scan running…", runAll: "Run Scan Now (all folders)", startingScan: "Starting scan…", lastScan: "Last scan: {{date}} — {{status}} — {{scanned}} scanned, {{newCount}} new, {{changed}} changed, {{removed}} removed, {{errors}} errors.", lastSuccessful: "Last successful scan: {{date}}"
  },
  settingsAnalysis: {
    ai: "AI", aiIntroBefore: "An optional local sidecar (", aiIntroAfter: ") turns photos into vectors for Find similar, describe-it search, smarter stacks, and AI tags. Nothing leaves your machine.", analyseAi: "Analyse photos with the AI sidecar when it's running", noProvider: "No AI provider configured (MEMORYLANE_AI_PROVIDER=none).", connected: "Connected to", notConnected: "Not connected to", startBefore: "Start it with", startAfter: "in a second terminal (see its README). Photos queue up meanwhile and are analysed once it's reachable; this card refreshes within a few seconds.", backgroundHelp: "Background processing that runs after scans — EXIF capture, keywords, stacking, and, when the AI sidecar is running, embeddings, photo tags, and faces. It pauses automatically while a scan is running.", retryFailed: "Retry failed",
    peopleHelp: "Finds faces and groups them into people you can name, then lets you browse photos of that person. It is off by default because faces are personal data; everything is computed and stored only on this machine and can be removed in one click.", findFaces: "Find and group faces (needs the AI sidecar)", faceModel: "Face model", switchTitle: "Switch face model?", switchMessage: "Every photo is re-analysed with the new model — a few minutes per few thousand photos, plus a one-time download. Names and your confirmed/rejected faces are kept. Press Regroup once it finishes.", switchModel: "Switch model", standardModel: "Standard — YuNet + SFace (open license)", arcfaceModel: "ArcFace — InsightFace buffalo_l (stronger, personal use only)", arcfaceHelp: "ArcFace separates similar faces much better, costs about 60% more time per photo and a one-time 190 MB download, and its weights are licensed for non-commercial use only.", modelUnavailable: "The running sidecar doesn't offer this model — update and restart it (npm run ai).", advancedPeople: "Advanced People settings", peopleAdvancedHelp: "If one person collects several similar-looking people, raise both strictness values (0.55–0.6 is a good start) and press Regroup. Stricter settings create more small groups to merge, which is easier than separating an incorrect group face by face.", matchStrictness: "Match strictness (min similarity, 0.3–0.9)", facesNeeded: "Faces needed to create a person (2–20)", groupStrictness: "Grouping strictness (0.3–0.9)", regroupTitleHelp: "Regroup all automatically grouped faces with the current settings. Names and your confirmed/rejected answers are kept.", regroupTitle: "Regroup faces?", regroupMessage: "Automatic groupings are redone with the current strictness. Names and your confirmed/rejected faces are kept.", regroup: "Regroup", regrouped: "Regrouped", regroupedMessage: "{{count}} new person, {{assigned}} faces assigned.", regroupedMessage_other: "{{count}} new people, {{assigned}} faces assigned.", regroupSettings: "Regroup with these settings", deleteTitle: "Delete all face data?", deleteMessage: "People, faces, and their vectors are removed. Your photos are untouched. Faces are detected again only while People is on.", deleteFaceData: "Delete face data", deleteAll: "Delete all face data",
    stacksHelp: "Bursts and near-identical tripod series are grouped into one grid item. Stacks you edit are never regrouped automatically.", advancedStacks: "Advanced stack settings", burstGap: "Burst gap (seconds)", visualSimilarity: "Visual similarity (max hash distance, 0–64)", aiSimilarity: "AI similarity (min cosine, 0.5–1)", tripodGap: "Tripod series gap (seconds)", recompute: "Recompute all stacks"
  },
  settingsStorage: { calculating: "Calculating…", intro: "MemoryLane's own cache and index — entirely separate from your photo folders, and safe to delete and rebuild with a rescan at any time.", location: "Location", sourceEnv: "Set by MEMORYLANE_DATA_DIR in the environment.", sourcePointer: "Chosen under Settings (the default location holds a pointer to it).", sourceDefault: "The OS default location.", pendingBefore: "Data was copied to", pendingAfter: "Restart MemoryLane to use it; the copy here can be deleted afterwards.", previews: "Previews (RAW fullscreen)", thumbnails: "Thumbnail cache", database: "Database (index, EXIF, embeddings)", vectors: "Vector index", faces: "Face crops", logs: "Logs", total: "Total", moveHelp: "Move to another disk (an empty folder, e.g.", or: "or", pathPlaceholder: "/absolute/path/to/empty/folder", copying: "Copying…", moveHere: "Move data here", copied: "Copied {{bytes}} to", restart: "Restart MemoryLane", switchThenDelete: "to switch; then delete", freeSpace: "to free the space.", useRefresh: "Use Refresh to calculate storage usage." },
  settingsAbout: { tagline: "A love letter to the art of photography.", free: "Free, MIT Licensed", authors: "Original Authors:", licenses: "Other Licenses and Attributions", openSource: "MemoryLane is built with open-source software. Key components include:", licenseMit: "React, React DOM, React Router, Fastify, better-sqlite3, Argon2, Zod, Nano ID, bmp-js, open, and p-limit — MIT License.", licenseLucide: "Lucide — ISC License.", licenseDotenv: "dotenv — BSD 2-Clause License.", licenseSharp: "Sharp and its bundled libvips distribution — Apache License 2.0 and LGPL v3 or later, respectively.", licenseExif: "ExifTool and exiftool-vendored — ExifTool uses the Perl Artistic License or GNU GPL; its Node wrapper is MIT licensed.", licenseFfmpeg: "FFmpeg — bundled through ffmpeg-static under GNU GPL v3 or later. FFprobe carries its applicable FFmpeg license; the wrapper is MIT licensed.", licenseTray: "Go systray and its supporting Go libraries power the desktop tray application under their respective open-source licenses.", plugins: "Optional plugins may include additional libraries, models, and license terms. Their license notices are distributed with each plugin package.", copyright: "Copyright and license notices for bundled dependencies remain the property of their respective authors and contributors. Full license texts are included with the distributed software where required." },
  coreBrowse: {
    home: { titleError: "Could not save the title. Try again.", media: "{{count}} media item", media_other: "{{count}} media items", folders: "{{count}} folder", folders_other: "{{count}} folders", years: "{{count}} year", years_other: "{{count}} years", random: "Random Memory", onThisDay: "This Day, Another Time", archive: "Photo Archive", archiveTitle: "Archive title", titlePlaceholder: "John's Albums", saving: "Saving…", editTitle: "Edit archive title", edit: "Edit", tier: { day: "Photos taken on this day across the years.", week: "No photos from this exact day yet — here's the same week across the years.", month: "Nothing from this week yet — here's the same month across the years." }, noDated: "No dated photos yet to pull memories from — dates come from photo metadata.", noFolders: "No photo folders configured yet. Head to Settings to add a folder to scan." },
    folder: { stackFailed: "Could not create the stack", markTitle: "Mark {{count}} item for deletion?", markTitle_other: "Mark {{count}} items for deletion?", markMessage: "They will leave normal browsing and appear in Cleanup. You can restore them there. No files will be moved yet.", mark: "Mark for deletion", markFailed: "Could not mark items", indexedItems: " and {{count}} indexed item in it", indexedItems_other: " and {{count}} indexed items in it", ignoreTitle: "Ignore “{{name}}”?", ignoreMessage: "MemoryLane will stop scanning this folder{{items}}, which will be removed from your library. Original files on disk are never touched — you can remove it from the ignore list in Settings and rescan later.", ignore: "Ignore folder", selected: "selected", selectShownTitle: "Select all {{count}} items currently shown", allShown: "All shown", clear: "Clear", invert: "Invert", marking: "Marking…", stackSelected: "Stack selected", done: "Done", selectHelp: "Select photos for cleanup or stacking", select: "Select", allFiles: "All files", more: "More options", ignoring: "Ignoring…", empty: "This folder is empty.", noPhotos: "No photos in this folder.", noVideos: "No videos in this folder.", noFilesRecursive: "No files in this folder or its subfolders.", noPhotosRecursive: "No photos in this folder or its subfolders.", noVideosRecursive: "No videos in this folder or its subfolders.", loadingMore: "Loading more ({{current}} / {{total}})…" },
    cleanup: { loadFailed: "Could not load Cleanup", moreFailed: "Could not load more", restoreItemFailed: "Could not restore item", moveTitle: "Move {{count}} item to trash?", moveTitle_other: "Move {{count}} items to trash?", moveMessage: "This will move {{size}} of original files, including paired RAW, Live Photo, and sidecar files, into visible _MemoryLane-Trash folders. You can restore them from Cleanup.", moveTrash: "Move to trash", moveFailures: "{{count}} item could not be moved: {{error}}", moveFailures_other: "{{count}} items could not be moved: {{error}}", unknownError: "Unknown error", moveFailed: "Could not move files", restoreFileFailed: "Could not restore file", deleteTitle: "Permanently delete {{filename}}?", deleteMessage: "This will permanently remove the files in _MemoryLane-Trash for this item. {{size}} or more may be deleted, including companion files. This cannot be undone in MemoryLane.", deletePermanently: "Delete permanently", deleteFailed: "Could not delete file", summary: "{{count}} marked item, hidden from browsing. Files moved to MemoryLane Trash can be restored here.", summary_other: "{{count}} marked items, hidden from browsing. Files moved to MemoryLane Trash can be restored here.", selectShown: "Select all shown", moveSelected: "Move {{count}} selected to trash", emptyTitle: "Nothing marked for cleanup", emptyHelp: "Open a folder, choose Select, select one or more photos, then choose Mark for deletion. Marking only hides them from normal browsing; no files move until you review them here.", browse: "Browse your library", previewUnavailable: "Preview unavailable", marked: "{{size}} · Marked {{date}}", inTrash: "In MemoryLane Trash", interrupted: "Move interrupted — restore files", originalUnavailable: "Original currently unavailable", selectTrash: "Select for trash", restoreLibrary: "Restore to library", restoreFiles: "Restore files" }
  },
  reportsUi: { lens: "Lens", camera: "Camera", make: "Make", aperture: "Aperture", iso: "ISO", focal: "Focal length", year: "Year", exifMatch: "{{count}} photo with EXIF data matches", exifMatch_other: "{{count}} photos with EXIF data match", analysisProgress: "View analysis progress", exploreMuseum: "Explore Gear Museum", exploreTimeline: "Explore Gear Timeline", export: "Export CSV", from: "From", to: "To", clearAll: "Clear all", moreFilters: "More filters", loadingPhotos: "Loading photos…", noMatch: "No photos match. EXIF data is captured during scans; if the library was indexed before this feature, the backfill under Settings → Analysis fills it in.", loadingMore: "Loading more ({{current}} / {{total}})…" },
  gearUi: { museumIntro: "A collection of the cameras that have captured your library.", timelineIntro: "Your camera history, laid out chronologically.", searchLenses: "Search lenses…", searchCameras: "Search cameras…", noExif: "No camera EXIF data found in your library yet.", cameras: "{{count}} camera", cameras_other: "{{count}} cameras", lenses: "{{count}} lens", lenses_other: "{{count}} lenses", timelineType: "Timeline gear type", cameraPlural: "Cameras", lensPlural: "Lenses", minPhotos: "Min photos", refresh: "Refresh from the gear museum service", sort: "Sort: {{value}}", sorts: { photos: "Most Photos", recent: "Recently Used", name: "Name" }, noTimeline: "No dated photos to build a timeline from.", yearTitle: "{{name}} — {{year}}: {{count}} photos ({{percent}}% of all photos that year)", memories: "{{count}} memory captured", memories_other: "{{count}} memories captured", viewReports: "View all photos in Reports", firstUsed: "First used", lastUsed: "Last used", mostLens: "Most used lens", places: "Places photographed", photosByYear: "Photos by year", hideDetails: "Hide technical details", showDetails: "Show technical details", brand: "Brand", released: "Released", weight: "Weight", size: "Size", isoRange: "ISO range", apertureRange: "Aperture range", noSpecs: "No specs resolved for this camera yet.", lensesUsed: "Lenses used with this camera", allLenses: "All lenses", photosFrom: "Photos from this camera", inYear: "in {{year}}", allYears: "Show all years", viewAll: "View all ({{count}})" },
  folderPicker: { choose: "Choose folder", choosing: "Choosing…", failed: "Could not open the folder picker" },
  onboardingAction: { startingScan: "Starting scan…" },
} as const;
