export const es = {
  common: {
    language: "Idioma", systemDefault: "Predeterminado del sistema", english: "Inglés", spanish: "Español", french: "Francés",
    loading: "Cargando…", cancel: "Cancelar", close: "Cerrar", save: "Guardar", remove: "Eliminar", retry: "Reintentar", refresh: "Actualizar",
    enabled: "Activado", disabled: "Desactivado", yes: "Sí", no: "No", photos: "{{count}} foto", photos_other: "{{count}} fotos",
    files: "{{count}} archivo", files_other: "{{count}} archivos", previous: "Anterior", next: "Siguiente", search: "Buscar", continue: "Continuar", ok: "Aceptar", yearsAgo: "hace {{count}} año", yearsAgo_other: "hace {{count}} años", all: "Todo", photosOnly: "Solo fotos", videosOnly: "Solo vídeos", filterMedia: "Filtrar por tipo de contenido",
    play: "Reproducir", pause: "Pausar", add: "Añadir", cover: "Portada", openPhoto: "Abrir foto", confirmedByYou: "Confirmado por ti", confirm: "Confirmar", yesThem: "Sí, es esta persona", notThem: "No es esta persona", notThisPerson: "No es esta persona",
    slideshowLabel: "Presentación de fotos; se muestra {{filename}}. Usa las flechas izquierda y derecha para navegar y espacio para reproducir o pausar.", openFile: "Abrir {{filename}}", stackExpand: "Pila de {{count}} — haz clic para ampliar", stackLabel: "Pila de {{count}}",
    tags: "Etiquetas", addTag: "Añadir etiqueta", removeTag: "Quitar la etiqueta {{name}}", addTagFailed: "No se pudo añadir la etiqueta", removeTagFailed: "No se pudo quitar la etiqueta",
    pageLoadTitle: "Carga inicial aproximada: solicitudes API e imágenes visibles. No incluye sondeos posteriores, cambios de presentación ni imágenes fuera de pantalla.", pageLoading: "Cargando página…", pageLoaded: "Página cargada en {{seconds}} s",
    applePreview: "El original está en iCloud — se muestra la vista previa de Apple.", openPhotos: "Abrir en Fotos", originalUnavailable: "Original no disponible", cachedThumbnail: "se muestra la miniatura en caché. Vuelve a conectar la unidad o carpeta para ver la resolución completa.",
  },
  navigation: {
    browse: "Explorar", favorites: "Favoritos", people: "Personas", library: "Biblioteca", locations: "Ubicaciones", tags: "Etiquetas",
    reports: "Informes", gearMuseum: "Museo de equipos", gearTimeline: "Cronología de equipos", cleanup: "Limpieza", settings: "Configuración",
    search: "Buscar", logout: "Cerrar sesión", libraryPages: "Páginas de la biblioteca", signedInSettings: "Sesión iniciada — ve a Configuración para cambiar tu contraseña",
  },
  auth: {
    signIn: "Iniciar sesión", username: "Usuario", password: "Contraseña", currentPassword: "Contraseña actual", newPassword: "Nueva contraseña",
    loginFailed: "No se pudo iniciar sesión", setupTitle: "Configurar MemoryLane", setupIntro: "Crea la cuenta de administración para este archivo.",
    createAccount: "Crear cuenta", creating: "Creando…", signingIn: "Iniciando sesión…", confirmPassword: "Confirmar contraseña",
    passwordsMismatch: "Las contraseñas no coinciden", changePassword: "Cambiar contraseña", passwordChanged: "Contraseña cambiada.",
    intro: "Vuelve a conectar con los recuerdos que ya están en tu archivo fotográfico.", welcome: "Te damos la bienvenida a MemoryLane", setupAccount: "Vamos a crear tu cuenta de administración.", setupFailed: "No se pudo completar la configuración",
  },
  settings: {
    title: "Configuración", folders: "Carpetas y exclusiones", analysis: "IA y análisis", plugins: "Complementos", storage: "Almacenamiento",
    network: "Red", account: "Cuenta", about: "Acerca de", theme: "Tema", museumTitle: "Servicio Museo de MemoryLane",
    museumIntro: "Controla el servicio opcional que enriquece la información de los equipos.", museumEnable: "Activar el servicio Museo de MemoryLane",
    museumHelp: "Está activado de forma predeterminada. Desactívalo si no necesitas el enriquecimiento del museo.", networkIntro: "Controla desde dónde se puede acceder a MemoryLane. Los cambios de red se aplican después de reiniciar MemoryLane.",
    allowRemote: "Permitir acceso desde otros equipos", allowRemoteHelp: "Está desactivado de forma predeterminada, por lo que MemoryLane solo está disponible en este equipo. Reinicia MemoryLane para aplicar el cambio.",
    signedInAs: "Sesión iniciada como {{username}}", appearance: "Apariencia",
    sections: "Secciones de configuración", scanFolders: "Carpetas de escaneo", ignoredFolders: "Carpetas ignoradas", removeIgnored: "Quitar de la lista de exclusión", scanning: "Escaneo", runningAnalysis: "Análisis en curso", people: "Personas", stacks: "Pilas", accountHeading: "Cuenta",
  },
  viewer: {
    close: "Cerrar visor", previous: "Foto anterior", next: "Foto siguiente", favorite: "Añadir a favoritos", unfavorite: "Quitar de favoritos",
    camera: "Cámara", lens: "Objetivo", focalLength: "Distancia focal: {{value}} mm", dimensions: "Dimensiones: {{width}} × {{height}}",
    type: "Tipo: {{type}}", file: "Archivo", folder: "Carpeta", similar: "Buscar similares", fullscreen: "Pantalla completa", exitFullscreen: "Salir de pantalla completa",
    apertureTitle: "Ver todas las fotos con esta apertura", focalTitle: "Ver todas las fotos con esta distancia focal", lensTitle: "Ver todas las fotos con este objetivo", cameraTitle: "Ver todas las fotos con esta cámara",
    playLive: "Reproducir Live Photo", openRaw: "Abrir el archivo RAW original", zoomOut: "Alejar", zoomIn: "Acercar", closeInfo: "Cerrar información", info: "Información", isoTitle: "Ver todas las fotos con este ISO",
  },
  pages: {
    favorites: "Favoritos", noFavorites: "Todavía no hay favoritos — marca una foto con una estrella en el visor o en una carpeta.",
    people: "Personas", locations: "Ubicaciones", tags: "Etiquetas", reports: "Informes", cleanup: "Limpieza", search: "Buscar",
    surprise: "Sorpréndeme", similar: "Fotos similares", loadingMap: "Cargando mapa…", noResults: "No se encontraron resultados.", gathering: "Recopilando recuerdos…", noIndexed: "Todavía no hay fotos indexadas — añade una carpeta y ejecuta un escaneo desde Configuración.",
    searchMode: "Modo de búsqueda", names: "Nombres", describeAi: "Descríbelo (IA)", textSearchPlaceholder: "Buscar carpetas, archivos, cámara u objetivo…", aiSearchPlaceholder: "un pájaro despegando del agua, un coche rojo de noche, nieve en las montañas…", searchFailed: "La búsqueda falló", folders: "Carpetas", photosVideos: "Fotos y vídeos", yourLibrary: "Tu biblioteca", cameras: "Cámaras", lenses: "Objetivos",
  },
  analysisProgress: {
    exif: "Metadatos EXIF", fingerprints: "Huellas visuales (pilas)", embeddings: "Vectores de IA (similares, búsqueda y pilas)", aiTags: "Etiquetas fotográficas de IA", imported: "Palabras clave importadas", faces: "Rostros (Personas)",
    off: "Desactivado", waiting: "Esperando al servicio", paused: "Pausado durante el escaneo", failing: "Con errores", working: "Procesando", retry: "Necesita reintento", done: "Terminado",
    underMinute: "menos de un minuto", aboutMinutes: "unos {{count}} min", aboutHours: "unas {{value}} h", nothing: "Todavía no hay nada que analizar.", scanPaused: "Hay un escaneo en curso; el análisis continuará al terminar.", left: "quedan {{eta}}", failed: "Falló {{count}} archivo", failed_other: "Fallaron {{count}} archivos", peopleOff: "Activa Personas abajo para empezar a buscar rostros.", aiOff: "El análisis de IA está desactivado arriba.", lastError: "último error:", fixRetry: "Corrige la causa y usa Reintentar fallidos en Configuración › Análisis.",
  },
  scanning: {
    noMedia: "Todavía no hay contenido indexado", photos: "{{count}} foto", photos_other: "{{count}} fotos", videos: "{{count}} vídeo", videos_other: "{{count}} vídeos", folders: "{{count}} carpeta", folders_other: "{{count}} carpetas", pending: "{{count}} pendientes", failed: "{{count}} fallidos",
    progress: "{{scanned}} archivos escaneados, {{newCount}} nuevos y {{errors}} errores hasta ahora.", generating: "Generando miniaturas:", thumbnailsDone: "Miniaturas terminadas:", of: "{{current}} de {{total}}", addFailed: "No se pudo añadir la carpeta", scanFailed: "No se pudo iniciar el escaneo",
    removeTitle: "¿Quitar esta carpeta de MemoryLane?", removeMessage: "{{path}} se quitará de la biblioteca. Los archivos originales nunca se modifican; solo se elimina el índice de MemoryLane para la carpeta.", removeFolder: "Quitar carpeta", pathPlaceholder: "p. ej., D:\\Fotos o /mnt/fotos", addFolder: "Añadir carpeta",
    orderHelp: "Este orden también determina cómo aparecen las carpetas en la página de inicio.", moveUp: "Subir", moveDown: "Bajar", enableToScan: "Activa esta carpeta para escanearla", scanning: "Escaneando…", scanNow: "Escanear ahora", enable: "Activar", disable: "Desactivar", remove: "Quitar", modernize: "{{count}} vídeo se puede modernizar →", modernize_other: "{{count}} vídeos se pueden modernizar →", none: "Todavía no se han añadido carpetas.",
  },
  stacks: {
    title: "Pila", titleDetail: "Pila · {{count}} fotos · {{kind}}", view: "Ver", setCover: "Usar como portada", setCoverHelp: "Usa la foto seleccionada como portada de esta pila", split: "Crear otra pila", splitHelp: "Mueve las fotos seleccionadas a su propia pila", remove: "Quitar de la pila", removeHelp: "Quita las fotos seleccionadas de esta pila (no se volverán a apilar automáticamente)",
    deleteTitle: "¿Eliminar esta pila?", deleteMessage: "Las fotos permanecen en la biblioteca; simplemente dejan de estar agrupadas y no se volverán a apilar automáticamente.", delete: "Eliminar pila", selectHelp: "Haz clic en las fotos para seleccionarlas.", selected: "{{count}} seleccionadas.", edited: "Editada por ti; el reapilado automático no modificará esta pila.", automatic: "Agrupada automáticamente.", error: "Algo salió mal",
  },
  pluginUi: {
    loadFailed: "No se pudieron cargar los complementos", genericError: "Algo salió mal.", installing: "Instalando {{name}}…", updating: "Actualizando {{name}}…", changeFailed: "No se pudo cambiar {{name}}", removeTitle: "¿Quitar {{name}}?", removeMessage: "El complemento se puede volver a descargar más adelante. Los datos indexados del núcleo se conservan.", removePlugin: "Quitar complemento", removed: "Complemento eliminado", removedMessage: "Se eliminó {{name}}.", removeFailed: "No se pudo eliminar {{name}}",
    required: "Obligatorio", optional: "Opcional", requires: "Requiere {{dependencies}}", logs: "Registros", logsUnavailable: "Registros no disponibles", install: "Instalar", update: "Actualizar", disable: "Desactivar", enable: "Activar", remove: "Quitar", updateIntro: "Las actualizaciones del núcleo y los complementos se comprueban a diario. Las actualizaciones de complementos se revierten si fallan al iniciar.", checkUpdates: "Buscar actualizaciones", updateFailed: "Falló la búsqueda de actualizaciones",
    core: "Núcleo", builtInRunning: "Integrado · v{{version}} · en ejecución", installed: "Instalados", installedHelp: "Componentes obligatorios y funciones opcionales que hayas añadido.", available: "Disponibles para instalar", availableHelp: "Instala solo las funciones que quieras.", nothingAvailable: "No hay nada más disponible para esta plataforma.", recentOutput: "Salida reciente del complemento", noOutput: "No hay salida registrada.", history: "Historial de actualizaciones",
  },
  onboarding: { step1: "Configuración de MemoryLane · Paso 1 de 2", welcome: "Te damos la bienvenida a MemoryLane", intro: "La forma más rápida de volver a descubrir fotos y vídeos antiguos y ver todo en un solo lugar, en tu propio equipo y sobre tus propios archivos. No se sube nada.", addFolders: "Añade tus carpetas de fotos", foldersHelp: "Indica las carpetas donde ya están tus fotos y vídeos. MemoryLane solo las lee; no modifica, renombra ni mueve nada. Puedes cambiarlas después en Configuración u omitir este paso.", step2: "Configuración de MemoryLane · Paso 2 de 2", optional: "Funciones opcionales", optionalHelp: "Instálalas ahora o añádelas después desde Configuración → Complementos.", storage: "Almacenamiento estimado del navegador: {{storage}}", feature: "Componente funcional", alsoInstalls: "También instala: {{dependencies}}", licenses: "Incluye software propio y avisos de licencia de las dependencias incluidas.", none: "No hay nada disponible para instalar; cierra para terminar la configuración.", preparing: "Preparando complementos…", installing: "Instalando…" },
  updates: { available: "MemoryLane {{version}} está disponible.", downloading: "Descargando de forma segura…", restart: "Reinicia para completar la actualización.", install: "Reiniciar e instalar", starting: "Iniciando…", dismiss: "Descartar actualización {{version}}" },
  onboardingRuntime: { starting: "Iniciando {{name}}…", installFailed: "La instalación del complemento falló" },
  applePhotos: { imageNotLocal: "La imagen no está en local", checkLocal: "Buscar copia local", title: "Fotos de Apple", devicePhotos: "Fotos del dispositivo Apple", unavailablePlatform: "No disponible en esta plataforma", readOnly: "Importación de solo lectura desde una fototeca local de Fotos de macOS.", notSynced: "Sin sincronizar", preparing: "Preparando el catálogo de Fotos{{elapsed}}", elapsed: " · {{seconds}} s transcurridos", syncSummary: "{{processed}} / {{total}} · {{status}}", skipped: " · {{count}} omitidos", service: "Servicio del complemento: {{status}}. MemoryLane lo inicia y supervisa automáticamente.", checking: "Comprobando…", permissionHint: "Si no se puede leer la fototeca, concede Acceso total al disco a MemoryLane en Ajustes del Sistema e inténtalo de nuevo.", path: "Ruta de la fototeca", addLibrary: "Añadir fototeca", detected: "Detectada: {{path}}", usePath: "Usar esta ruta", fullDiskAccess: "MemoryLane necesita Acceso total al disco para leer esta fototeca. Abre Ajustes del Sistema → Privacidad y seguridad → Acceso total al disco, activa MemoryLane, ciérralo por completo y vuelve a abrirlo.", noLibraries: "Aún no se han añadido fototecas.", indexed: "{{count}} indexados · {{summary}}", availability: "{{previewOnly}} solo vista previa · {{unavailable}} no disponibles", previousError: "Error de sincronización anterior: {{error}}", syncNow: "Sincronizar ahora" },
  appleBrowse: { loadFailed: "No se pudieron cargar las Fotos de Apple", openFailed: "No se pudo abrir Fotos", noLocal: "Aún no hay una imagen local utilizable. Abre la foto en Fotos e inténtalo de nuevo.", checkFailed: "No se pudo comprobar la copia local", moreFailed: "No se pudieron cargar más fotos", markTitle: "¿Marcar {{count}} elemento de Fotos de Apple?", markTitle_other: "¿Marcar {{count}} elementos de Fotos de Apple?", markMessage: "Desaparecerán de la navegación de MemoryLane y permanecerán en Limpieza. No se cambiará ningún archivo de la fototeca.", mark: "Marcar para eliminar", markFailed: "No se pudieron marcar los elementos de Fotos de Apple", breadcrumbs: "Ruta de navegación de Fotos de Apple", allPhotos: "Todas las fotos", unknownDate: "Fecha desconocida", items: "{{count}} elemento", items_other: "{{count}} elementos", select: "Seleccionar", selected: "{{count}} seleccionados", selectShown: "Seleccionar los {{count}} mostrados", none: "Ninguno", invert: "Invertir mostrados", loadMore: "Cargar más", loading: "Cargando Fotos de Apple…" },
  appleErrors: { notRunning: "no está en ejecución", addFailed: "No se pudo añadir la fototeca", syncFailed: "No se pudo iniciar la sincronización" },
  settingsUi: {
    theme: { light: "Claro", dark: "Oscuro", dusk: "Atardecer", gallery: "Galería" }, passwordMismatch: "Las contraseñas nuevas no coinciden", passwordFailed: "No se pudo cambiar la contraseña", newPasswordHint: "Nueva contraseña (mín. 8 caracteres)", confirmNewPassword: "Confirmar nueva contraseña", passwordChanged: "Contraseña cambiada. Mantendrás la sesión aquí; se cerraron las sesiones de los demás dispositivos.", changing: "Cambiando…",
    moveTitle: "¿Mover los datos de MemoryLane?", moveMessageBefore: "Todo (base de datos, miniaturas, vistas previas, vectores y recortes de rostros) se copia ahora en", moveMessageAfter: "— aproximadamente un minuto por GB, mientras MemoryLane sigue funcionando. Después, reinícialo para usar la nueva ubicación; la copia anterior permanece hasta que la elimines.", copyData: "Copiar datos", moveFailed: "No se pudieron mover los datos", recomputed: "Pilas recalculadas en {{count}} carpeta.", recomputed_other: "Pilas recalculadas en {{count}} carpetas.", storageFailed: "No se pudo cargar el uso de almacenamiento",
    scanFoldersHelp: "Añade carpetas que contengan tus fotos y vídeos. MemoryLane nunca modifica, renombra ni mueve los originales.", ignoredHelp: "Carpetas que MemoryLane omite en cada escaneo. Pulsa «Ignorar carpeta» mientras exploras una carpeta para añadirla aquí. Quitarla de esta lista no restaura nada; se recogerá de nuevo en el próximo escaneo.", noIgnored: "No hay carpetas ignoradas.", scanEvery: "Escanear automáticamente cada", days: "días", scanRunning: "Escaneo en curso…", runAll: "Escanear ahora (todas las carpetas)", startingScan: "Iniciando escaneo…", lastScan: "Último escaneo: {{date}} — {{status}} — {{scanned}} escaneados, {{newCount}} nuevos, {{changed}} cambiados, {{removed}} eliminados, {{errors}} errores.", lastSuccessful: "Último escaneo correcto: {{date}}"
  },
  settingsAnalysis: {
    ai: "IA", aiIntroBefore: "Un servicio local opcional (", aiIntroAfter: ") convierte las fotos en vectores para buscar similares, describir búsquedas, crear pilas más inteligentes y etiquetas de IA. Nada sale de tu equipo.", analyseAi: "Analizar fotos con el servicio de IA cuando esté en ejecución", noProvider: "No hay proveedor de IA configurado (MEMORYLANE_AI_PROVIDER=none).", connected: "Conectado a", notConnected: "Sin conexión con", startBefore: "Inícialo con", startAfter: "en otra terminal (consulta su README). Las fotos quedan en cola y se analizan cuando esté disponible; esta tarjeta se actualiza en unos segundos.", backgroundHelp: "Procesamiento en segundo plano tras los escaneos: captura EXIF, palabras clave, pilas y, cuando funciona el servicio de IA, vectores, etiquetas y rostros. Se pausa automáticamente durante un escaneo.", retryFailed: "Reintentar fallidos",
    peopleHelp: "Busca rostros y los agrupa en personas que puedes nombrar para explorar sus fotos. Está desactivado por defecto porque los rostros son datos personales; todo se calcula y almacena solo en este equipo y se puede eliminar con un clic.", findFaces: "Buscar y agrupar rostros (requiere el servicio de IA)", faceModel: "Modelo facial", switchTitle: "¿Cambiar el modelo facial?", switchMessage: "Cada foto se vuelve a analizar con el nuevo modelo; tarda unos minutos por cada varios miles de fotos y requiere una descarga inicial. Se conservan los nombres y rostros confirmados o rechazados. Pulsa Reagrupar al terminar.", switchModel: "Cambiar modelo", standardModel: "Estándar — YuNet + SFace (licencia abierta)", arcfaceModel: "ArcFace — InsightFace buffalo_l (más preciso, solo uso personal)", arcfaceHelp: "ArcFace distingue mucho mejor rostros parecidos, tarda aproximadamente un 60 % más por foto, requiere una descarga inicial de 190 MB y sus pesos solo permiten uso no comercial.", modelUnavailable: "El servicio en ejecución no ofrece este modelo; actualízalo y reinícialo (npm run ai).", advancedPeople: "Configuración avanzada de Personas", peopleAdvancedHelp: "Si una persona reúne a varias personas parecidas, aumenta ambos valores de exigencia (0,55–0,6 es un buen inicio) y pulsa Reagrupar. Una configuración más estricta crea más grupos pequeños fáciles de combinar.", matchStrictness: "Exigencia de coincidencia (similitud mín., 0,3–0,9)", facesNeeded: "Rostros necesarios para crear una persona (2–20)", groupStrictness: "Exigencia de agrupación (0,3–0,9)", regroupTitleHelp: "Reagrupar los rostros automáticos con la configuración actual. Se conservan nombres y respuestas.", regroupTitle: "¿Reagrupar rostros?", regroupMessage: "Las agrupaciones automáticas se rehacen con la exigencia actual. Se conservan nombres y rostros confirmados o rechazados.", regroup: "Reagrupar", regrouped: "Reagrupados", regroupedMessage: "{{count}} persona nueva, {{assigned}} rostros asignados.", regroupedMessage_other: "{{count}} personas nuevas, {{assigned}} rostros asignados.", regroupSettings: "Reagrupar con esta configuración", deleteTitle: "¿Eliminar todos los datos faciales?", deleteMessage: "Se eliminan personas, rostros y sus vectores. Tus fotos no cambian. Los rostros solo se vuelven a detectar mientras Personas esté activado.", deleteFaceData: "Eliminar datos faciales", deleteAll: "Eliminar todos los datos faciales",
    stacksHelp: "Las ráfagas y series de trípode casi idénticas se agrupan en un elemento de la cuadrícula. Las pilas que edites nunca se reagruparán automáticamente.", advancedStacks: "Configuración avanzada de pilas", burstGap: "Intervalo de ráfaga (segundos)", visualSimilarity: "Similitud visual (distancia hash máx., 0–64)", aiSimilarity: "Similitud de IA (coseno mín., 0,5–1)", tripodGap: "Intervalo de serie con trípode (segundos)", recompute: "Recalcular todas las pilas"
  },
  settingsStorage: { calculating: "Calculando…", intro: "La caché y el índice de MemoryLane están completamente separados de tus carpetas de fotos; puedes eliminarlos y reconstruirlos con un escaneo en cualquier momento.", location: "Ubicación", sourceEnv: "Definida por MEMORYLANE_DATA_DIR en el entorno.", sourcePointer: "Elegida en Configuración (la ubicación predeterminada contiene un enlace a ella).", sourceDefault: "Ubicación predeterminada del sistema operativo.", pendingBefore: "Los datos se copiaron en", pendingAfter: "Reinicia MemoryLane para usarlos; después puedes eliminar la copia de aquí.", previews: "Vistas previas (RAW a pantalla completa)", thumbnails: "Caché de miniaturas", database: "Base de datos (índice, EXIF, vectores)", vectors: "Índice vectorial", faces: "Recortes de rostros", logs: "Registros", total: "Total", moveHelp: "Mover a otro disco (una carpeta vacía, p. ej.", or: "o", pathPlaceholder: "/ruta/absoluta/a/carpeta/vacía", copying: "Copiando…", moveHere: "Mover datos aquí", copied: "Se copiaron {{bytes}} en", restart: "Reinicia MemoryLane", switchThenDelete: "para cambiar; después elimina", freeSpace: "para liberar espacio.", useRefresh: "Usa Actualizar para calcular el uso del almacenamiento." },
  settingsAbout: { tagline: "Una carta de amor al arte de la fotografía.", free: "Gratis, con licencia MIT", authors: "Autores originales:", licenses: "Otras licencias y atribuciones", openSource: "MemoryLane está creado con software de código abierto. Sus componentes principales incluyen:", licenseMit: "React, React DOM, React Router, Fastify, better-sqlite3, Argon2, Zod, Nano ID, bmp-js, open y p-limit — Licencia MIT.", licenseLucide: "Lucide — Licencia ISC.", licenseDotenv: "dotenv — Licencia BSD de 2 cláusulas.", licenseSharp: "Sharp y su distribución libvips — Licencia Apache 2.0 y LGPL v3 o posterior, respectivamente.", licenseExif: "ExifTool y exiftool-vendored — ExifTool usa la licencia Artistic de Perl o GNU GPL; su envoltorio de Node tiene licencia MIT.", licenseFfmpeg: "FFmpeg — incluido mediante ffmpeg-static bajo GNU GPL v3 o posterior. FFprobe conserva su licencia de FFmpeg y el envoltorio tiene licencia MIT.", licenseTray: "Go systray y sus bibliotecas de Go proporcionan la aplicación de bandeja bajo sus respectivas licencias de código abierto.", plugins: "Los complementos opcionales pueden incluir bibliotecas, modelos y condiciones adicionales. Sus avisos de licencia se distribuyen con cada complemento.", copyright: "Los avisos de copyright y licencia de las dependencias pertenecen a sus respectivos autores y colaboradores. Los textos completos se incluyen con el software distribuido cuando es necesario." },
  coreBrowse: {
    home: { titleError: "No se pudo guardar el título. Inténtalo de nuevo.", media: "{{count}} elemento", media_other: "{{count}} elementos", folders: "{{count}} carpeta", folders_other: "{{count}} carpetas", years: "{{count}} año", years_other: "{{count}} años", random: "Recuerdo al azar", onThisDay: "Este día, en otro momento", archive: "Archivo fotográfico", archiveTitle: "Título del archivo", titlePlaceholder: "Álbumes de Juan", saving: "Guardando…", editTitle: "Editar título del archivo", edit: "Editar", tier: { day: "Fotos tomadas este día a lo largo de los años.", week: "Aún no hay fotos de este día exacto; aquí tienes la misma semana a lo largo de los años.", month: "Aún no hay nada de esta semana; aquí tienes el mismo mes a lo largo de los años." }, noDated: "Aún no hay fotos con fecha para recuperar recuerdos; las fechas proceden de los metadatos.", noFolders: "Aún no hay carpetas de fotos configuradas. Ve a Configuración para añadir una carpeta." },
    folder: { stackFailed: "No se pudo crear la pila", markTitle: "¿Marcar {{count}} elemento para eliminar?", markTitle_other: "¿Marcar {{count}} elementos para eliminar?", markMessage: "Dejarán de aparecer en la navegación normal y pasarán a Limpieza. Puedes restaurarlos allí. Aún no se moverá ningún archivo.", mark: "Marcar para eliminar", markFailed: "No se pudieron marcar los elementos", indexedItems: " y {{count}} elemento indexado que contiene", indexedItems_other: " y {{count}} elementos indexados que contiene", ignoreTitle: "¿Ignorar «{{name}}»?", ignoreMessage: "MemoryLane dejará de escanear esta carpeta{{items}}, que se quitará de tu biblioteca. Los archivos originales nunca se modifican; puedes quitarla de la lista de exclusión y volver a escanear más adelante.", ignore: "Ignorar carpeta", selected: "seleccionados", selectShownTitle: "Seleccionar los {{count}} elementos mostrados", allShown: "Todos los mostrados", clear: "Limpiar", invert: "Invertir", marking: "Marcando…", stackSelected: "Apilar seleccionados", done: "Listo", selectHelp: "Seleccionar fotos para limpiar o apilar", select: "Seleccionar", allFiles: "Todos los archivos", more: "Más opciones", ignoring: "Ignorando…", empty: "Esta carpeta está vacía.", noPhotos: "No hay fotos en esta carpeta.", noVideos: "No hay vídeos en esta carpeta.", noFilesRecursive: "No hay archivos en esta carpeta ni en sus subcarpetas.", noPhotosRecursive: "No hay fotos en esta carpeta ni en sus subcarpetas.", noVideosRecursive: "No hay vídeos en esta carpeta ni en sus subcarpetas.", loadingMore: "Cargando más ({{current}} / {{total}})…" },
    cleanup: { loadFailed: "No se pudo cargar Limpieza", moreFailed: "No se pudo cargar más", restoreItemFailed: "No se pudo restaurar el elemento", moveTitle: "¿Mover {{count}} elemento a la papelera?", moveTitle_other: "¿Mover {{count}} elementos a la papelera?", moveMessage: "Se moverán {{size}} de archivos originales, incluidos RAW emparejados, Live Photos y archivos auxiliares, a carpetas visibles _MemoryLane-Trash. Puedes restaurarlos desde Limpieza.", moveTrash: "Mover a la papelera", moveFailures: "No se pudo mover {{count}} elemento: {{error}}", moveFailures_other: "No se pudieron mover {{count}} elementos: {{error}}", unknownError: "Error desconocido", moveFailed: "No se pudieron mover los archivos", restoreFileFailed: "No se pudo restaurar el archivo", deleteTitle: "¿Eliminar {{filename}} permanentemente?", deleteMessage: "Esto eliminará permanentemente los archivos de _MemoryLane-Trash para este elemento. Se pueden eliminar {{size}} o más, incluidos los archivos asociados. No se puede deshacer en MemoryLane.", deletePermanently: "Eliminar permanentemente", deleteFailed: "No se pudo eliminar el archivo", summary: "{{count}} elemento marcado y oculto de la navegación. Los archivos movidos a la papelera de MemoryLane se pueden restaurar aquí.", summary_other: "{{count}} elementos marcados y ocultos de la navegación. Los archivos movidos a la papelera de MemoryLane se pueden restaurar aquí.", selectShown: "Seleccionar todos los mostrados", moveSelected: "Mover {{count}} seleccionados a la papelera", emptyTitle: "Nada marcado para limpiar", emptyHelp: "Abre una carpeta, elige Seleccionar, marca una o más fotos y elige Marcar para eliminar. Esto solo las oculta de la navegación; ningún archivo se mueve hasta que lo revises aquí.", browse: "Explorar tu biblioteca", previewUnavailable: "Vista previa no disponible", marked: "{{size}} · Marcado el {{date}}", inTrash: "En la papelera de MemoryLane", interrupted: "Movimiento interrumpido — restaura los archivos", originalUnavailable: "Original no disponible actualmente", selectTrash: "Seleccionar para la papelera", restoreLibrary: "Restaurar en la biblioteca", restoreFiles: "Restaurar archivos" }
  },
  reportsUi: { lens: "Objetivo", camera: "Cámara", make: "Marca", aperture: "Apertura", iso: "ISO", focal: "Distancia focal", year: "Año", exifMatch: "Coincide {{count}} foto con datos EXIF", exifMatch_other: "Coinciden {{count}} fotos con datos EXIF", analysisProgress: "Ver progreso del análisis", exploreMuseum: "Explorar el Museo de equipos", exploreTimeline: "Explorar la cronología de equipos", export: "Exportar CSV", from: "Desde", to: "Hasta", clearAll: "Borrar todo", moreFilters: "Más filtros", loadingPhotos: "Cargando fotos…", noMatch: "No hay fotos coincidentes. Los datos EXIF se capturan durante los escaneos; si la biblioteca se indexó antes, el procesamiento en Configuración → Análisis los completa.", loadingMore: "Cargando más ({{current}} / {{total}})…" },
  gearUi: { museumIntro: "Una colección de las cámaras que han capturado tu biblioteca.", timelineIntro: "La historia de tus cámaras, ordenada cronológicamente.", searchLenses: "Buscar objetivos…", searchCameras: "Buscar cámaras…", noExif: "Aún no hay datos EXIF de cámaras en tu biblioteca.", cameras: "{{count}} cámara", cameras_other: "{{count}} cámaras", lenses: "{{count}} objetivo", lenses_other: "{{count}} objetivos", timelineType: "Tipo de equipo de la cronología", cameraPlural: "Cámaras", lensPlural: "Objetivos", minPhotos: "Fotos mín.", refresh: "Actualizar desde el servicio del museo", sort: "Ordenar: {{value}}", sorts: { photos: "Más fotos", recent: "Uso reciente", name: "Nombre" }, noTimeline: "No hay fotos con fecha para crear una cronología.", yearTitle: "{{name}} — {{year}}: {{count}} fotos ({{percent}} % de todas las fotos de ese año)", memories: "{{count}} recuerdo capturado", memories_other: "{{count}} recuerdos capturados", viewReports: "Ver todas las fotos en Informes", firstUsed: "Primer uso", lastUsed: "Último uso", mostLens: "Objetivo más usado", places: "Lugares fotografiados", photosByYear: "Fotos por año", hideDetails: "Ocultar detalles técnicos", showDetails: "Mostrar detalles técnicos", brand: "Marca", released: "Lanzamiento", weight: "Peso", size: "Tamaño", isoRange: "Rango ISO", apertureRange: "Rango de apertura", noSpecs: "Aún no se han obtenido especificaciones para esta cámara.", lensesUsed: "Objetivos usados con esta cámara", allLenses: "Todos los objetivos", photosFrom: "Fotos de esta cámara", inYear: "en {{year}}", allYears: "Mostrar todos los años", viewAll: "Ver todo ({{count}})" },
} as const;
