export const fr = {
  common: {
    language: "Langue", systemDefault: "Langue du système", english: "Anglais", spanish: "Espagnol", french: "Français",
    loading: "Chargement…", cancel: "Annuler", close: "Fermer", save: "Enregistrer", remove: "Supprimer", retry: "Réessayer", refresh: "Actualiser",
    enabled: "Activé", disabled: "Désactivé", yes: "Oui", no: "Non", photos: "{{count}} photo", photos_other: "{{count}} photos",
    files: "{{count}} fichier", files_other: "{{count}} fichiers", previous: "Précédent", next: "Suivant", search: "Rechercher", continue: "Continuer", ok: "OK", yearsAgo: "il y a {{count}} an", yearsAgo_other: "il y a {{count}} ans", all: "Tout", photosOnly: "Photos uniquement", videosOnly: "Vidéos uniquement", filterMedia: "Filtrer par type de média",
    play: "Lire", pause: "Pause", add: "Ajouter", cover: "Couverture", openPhoto: "Ouvrir la photo", confirmedByYou: "Confirmé par vous", confirm: "Confirmer", yesThem: "Oui, c'est cette personne", notThem: "Ce n'est pas cette personne", notThisPerson: "Pas cette personne",
    slideshowLabel: "Diaporama photo affichant actuellement {{filename}}. Utilisez les flèches gauche et droite pour naviguer et la barre d’espace pour lire ou mettre en pause.", openFile: "Ouvrir {{filename}}", stackExpand: "Pile de {{count}} — cliquer pour développer", stackLabel: "Pile de {{count}}",
    tags: "Étiquettes", addTag: "Ajouter une étiquette", removeTag: "Retirer l’étiquette {{name}}", addTagFailed: "Impossible d’ajouter l’étiquette", removeTagFailed: "Impossible de retirer l’étiquette",
    pageLoadTitle: "Chargement initial approximatif : requêtes API et images visibles. Exclut les interrogations ultérieures, les changements de diaporama et les images hors écran.", pageLoading: "Chargement de la page…", pageLoaded: "Page chargée en {{seconds}} s",
    applePreview: "L’original est dans iCloud — aperçu Apple affiché.", openPhotos: "Ouvrir dans Photos", originalUnavailable: "Original indisponible", cachedThumbnail: "miniature en cache affichée. Reconnectez le disque ou le dossier pour voir la pleine résolution.",
  },
  navigation: {
    browse: "Parcourir", favorites: "Favoris", people: "Personnes", library: "Bibliothèque", locations: "Lieux", tags: "Étiquettes",
    reports: "Rapports", gearMuseum: "Musée du matériel", gearTimeline: "Chronologie du matériel", cleanup: "Nettoyage", settings: "Paramètres",
    search: "Rechercher", logout: "Se déconnecter", libraryPages: "Pages de la bibliothèque", signedInSettings: "Connecté — ouvrez les Paramètres pour modifier votre mot de passe",
  },
  auth: {
    signIn: "Se connecter", username: "Nom d’utilisateur", password: "Mot de passe", currentPassword: "Mot de passe actuel", newPassword: "Nouveau mot de passe",
    loginFailed: "Échec de la connexion", setupTitle: "Configurer MemoryLane", setupIntro: "Créez le compte administrateur de cette archive.",
    createAccount: "Créer le compte", creating: "Création…", signingIn: "Connexion…", confirmPassword: "Confirmer le mot de passe",
    passwordsMismatch: "Les mots de passe ne correspondent pas", changePassword: "Modifier le mot de passe", passwordChanged: "Mot de passe modifié.",
    intro: "Retrouvez les souvenirs déjà présents dans vos archives photo.", welcome: "Bienvenue dans MemoryLane", setupAccount: "Créons votre compte administrateur.", setupFailed: "Échec de la configuration",
  },
  settings: {
    title: "Paramètres", folders: "Dossiers et exclusions", analysis: "IA et analyse", plugins: "Extensions", storage: "Stockage",
    network: "Réseau", account: "Compte", about: "À propos", theme: "Thème", museumTitle: "Service Musée MemoryLane",
    museumIntro: "Contrôlez le service facultatif qui enrichit les informations sur le matériel.", museumEnable: "Activer le service Musée MemoryLane",
    museumHelp: "Désactivé par défaut. Activez-le pour obtenir les informations facultatives sur les appareils et objectifs du Service Musée.", networkIntro: "Contrôlez depuis où MemoryLane est accessible. Les modifications réseau prennent effet après le redémarrage de MemoryLane.",
    allowRemote: "Autoriser l’accès depuis d’autres ordinateurs", allowRemoteHelp: "Désactivé par défaut, MemoryLane n’est donc disponible que sur cet ordinateur. Redémarrez MemoryLane pour appliquer ce changement.",
    signedInAs: "Connecté en tant que {{username}}", appearance: "Apparence",
    sections: "Sections des paramètres", scanFolders: "Dossiers analysés", ignoredFolders: "Dossiers ignorés", removeIgnored: "Retirer de la liste d’exclusion", scanning: "Analyse des dossiers", runningAnalysis: "Analyse en cours", people: "Personnes", stacks: "Piles", accountHeading: "Compte",
  },
  viewer: {
    close: "Fermer la visionneuse", previous: "Photo précédente", next: "Photo suivante", favorite: "Ajouter aux favoris", unfavorite: "Retirer des favoris",
    camera: "Appareil", lens: "Objectif", focalLength: "Distance focale : {{value}} mm", dimensions: "Dimensions : {{width}} × {{height}}",
    type: "Type : {{type}}", file: "Fichier", folder: "Dossier", similar: "Trouver des photos similaires", fullscreen: "Plein écran", exitFullscreen: "Quitter le plein écran",
    apertureTitle: "Voir toutes les photos avec cette ouverture", focalTitle: "Voir toutes les photos avec cette distance focale", lensTitle: "Voir toutes les photos avec cet objectif", cameraTitle: "Voir toutes les photos avec cet appareil",
    playLive: "Lire la Live Photo", openRaw: "Ouvrir le fichier RAW original", zoomOut: "Dézoomer", zoomIn: "Zoomer", closeInfo: "Fermer les informations", info: "Informations", isoTitle: "Voir toutes les photos avec cette sensibilité ISO",
  },
  pages: {
    favorites: "Favoris", noFavorites: "Aucun favori — ajoutez une étoile à une photo dans la visionneuse ou dans un dossier.",
    people: "Personnes", locations: "Lieux", tags: "Étiquettes", reports: "Rapports", cleanup: "Nettoyage", search: "Rechercher",
    surprise: "Surprenez-moi", similar: "Photos similaires", loadingMap: "Chargement de la carte…", noResults: "Aucun résultat.", gathering: "Recherche de souvenirs…", noIndexed: "Aucune photo indexée — ajoutez un dossier et lancez une analyse depuis les Paramètres.",
    searchMode: "Mode de recherche", names: "Noms", describeAi: "Décrire (IA)", textSearchPlaceholder: "Rechercher des dossiers, fichiers, appareils ou objectifs…", aiSearchPlaceholder: "un oiseau décollant de l’eau, une voiture rouge la nuit, de la neige en montagne…", searchFailed: "La recherche a échoué", folders: "Dossiers", photosVideos: "Photos et vidéos", yourLibrary: "Votre bibliothèque", cameras: "Appareils", lenses: "Objectifs",
  },
  analysisProgress: {
    exif: "Métadonnées EXIF", fingerprints: "Empreintes visuelles (piles)", embeddings: "Vecteurs IA (similaires, recherche et piles)", aiTags: "Étiquettes photo IA", imported: "Mots-clés importés", faces: "Visages (Personnes)",
    off: "Désactivé", waiting: "En attente du service", paused: "En pause pendant l’analyse", failing: "En échec", working: "En cours", retry: "Nouvel essai requis", done: "Terminé",
    underMinute: "moins d’une minute", aboutMinutes: "environ {{count}} min", aboutHours: "environ {{value}} h", nothing: "Rien à analyser pour le moment.", scanPaused: "Une analyse des dossiers est en cours ; le traitement reprendra ensuite.", left: "{{eta}} restantes", failed: "{{count}} fichier en échec", failed_other: "{{count}} fichiers en échec", peopleOff: "Activez Personnes ci-dessous pour commencer à rechercher les visages.", aiOff: "L’analyse IA est désactivée ci-dessus.", lastError: "dernière erreur :", fixRetry: "Corrigez la cause, puis utilisez Réessayer les échecs dans Paramètres › Analyse.",
  },
  scanning: {
    noMedia: "Aucun média indexé — cliquez sur Analyser", photos: "{{count}} photo", photos_other: "{{count}} photos", videos: "{{count}} vidéo", videos_other: "{{count}} vidéos", folders: "{{count}} dossier", folders_other: "{{count}} dossiers", pending: "{{count}} en attente", failed: "{{count}} en échec",
    progress: "{{scanned}} fichiers analysés, {{newCount}} nouveaux et {{errors}} erreurs pour le moment.", generating: "Création des miniatures :", thumbnailsDone: "Miniatures terminées :", of: "{{current}} sur {{total}}", addFailed: "Impossible d’ajouter le dossier", scanFailed: "Impossible de lancer l’analyse",
    removeTitle: "Retirer ce dossier de MemoryLane ?", removeMessage: "{{path}} sera retiré de la bibliothèque. Les fichiers originaux ne sont jamais modifiés ; seul l’index MemoryLane du dossier est supprimé.", removeFolder: "Retirer le dossier", pathLabel: "Chemin du dossier", pathHelp: "Saisissez le chemin complet d’un dossier sur l’ordinateur qui exécute MemoryLane.", pathPlaceholder: "Exemple : D:\\Photos ou /mnt/photos", pathExamples: "Exemples : Windows : D:\\Photos · macOS : /Users/nom/Images · Linux : /mnt/photos", addFolder: "Ajouter un dossier",
    orderHelp: "Faites glisser les dossiers pour les réordonner. Cet ordre est aussi utilisé sur la page d’accueil.", dragToReorder: "Faire glisser pour réordonner", reorderFailed: "Impossible d’enregistrer l’ordre des dossiers", moveUp: "Monter", moveDown: "Descendre", enableToScan: "Activez ce dossier pour l’analyser", scanning: "Analyse…", scanNow: "Analyser", enable: "Activer", disable: "Désactiver", remove: "Retirer", modernize: "{{count}} vidéo peut être modernisée →", modernize_other: "{{count}} vidéos peuvent être modernisées →", none: "Aucun dossier ajouté.",
  },
  stacks: {
    title: "Pile", titleDetail: "Pile · {{count}} photos · {{kind}}", view: "Afficher", setCover: "Définir comme couverture", setCoverHelp: "Utiliser la photo sélectionnée comme couverture de cette pile", split: "Créer une nouvelle pile", splitHelp: "Déplacer les photos sélectionnées dans leur propre pile", remove: "Retirer de la pile", removeHelp: "Retirer les photos sélectionnées de cette pile (elles ne seront plus empilées automatiquement)",
    deleteTitle: "Supprimer cette pile ?", deleteMessage: "Les photos restent dans la bibliothèque ; elles ne seront simplement plus regroupées ni empilées automatiquement.", delete: "Supprimer la pile", selectHelp: "Cliquez sur les photos pour les sélectionner.", selected: "{{count}} sélectionnées.", edited: "Modifiée par vous ; l’empilage automatique laissera cette pile intacte.", automatic: "Regroupée automatiquement.", error: "Une erreur s’est produite",
  },
  pluginUi: {
    loadFailed: "Impossible de charger les extensions", genericError: "Une erreur s’est produite.", installing: "Installation de {{name}}…", updating: "Mise à jour de {{name}}…", changeFailed: "Impossible de modifier {{name}}", removeTitle: "Retirer {{name}} ?", removeMessage: "L’extension pourra être téléchargée à nouveau. Les données indexées du noyau sont conservées.", removePlugin: "Retirer l’extension", removed: "Extension retirée", removedMessage: "{{name}} a été retirée.", removeFailed: "Impossible de retirer {{name}}",
    required: "Requise", optional: "Facultative", requires: "Nécessite {{dependencies}}", logs: "Journaux", logsUnavailable: "Journaux indisponibles", install: "Installer", update: "Mettre à jour", disable: "Désactiver", enable: "Activer", remove: "Retirer", updateIntro: "Les mises à jour du noyau et des extensions sont vérifiées chaque jour. Une extension est restaurée si elle échoue au démarrage.", checkUpdates: "Rechercher des mises à jour", updateFailed: "Échec de la recherche de mises à jour",
    core: "Noyau", builtInRunning: "Intégré · v{{version}} · en cours d’exécution", installed: "Installées", installedHelp: "Composants requis et fonctionnalités facultatives ajoutées.", available: "Disponibles à l’installation", availableHelp: "Installez uniquement les fonctionnalités souhaitées.", nothingAvailable: "Aucune autre extension disponible pour cette plateforme.", recentOutput: "Sortie récente de l’extension", noOutput: "Aucune sortie enregistrée.", history: "Historique des mises à jour",
  },
  onboarding: { step1: "Configuration de MemoryLane · Étape 1 sur 2", welcome: "Bienvenue dans MemoryLane", intro: "Le moyen le plus rapide de redécouvrir vos anciennes photos et vidéos et de tout voir au même endroit, sur votre ordinateur et dans vos propres fichiers. Rien n’est envoyé ailleurs.", addFolders: "Ajoutez vos dossiers photo", foldersHelp: "Indiquez les dossiers où se trouvent déjà vos photos et vidéos. MemoryLane les lit uniquement ; rien n’est modifié, renommé ou déplacé. Vous pourrez les modifier dans les Paramètres ou ignorer cette étape.", step2: "Configuration de MemoryLane · Étape 2 sur 2", optional: "Fonctionnalités facultatives", optionalHelp: "Installez-les maintenant ou ajoutez-les plus tard depuis Paramètres → Extensions.", storage: "Estimation du stockage du navigateur : {{storage}}", feature: "Composant fonctionnel", alsoInstalls: "Installe également : {{dependencies}}", licenses: "Inclut des logiciels propriétaires au projet et les avis de licence des dépendances intégrées.", none: "Rien à installer pour le moment ; fermez pour terminer la configuration.", preparing: "Préparation des extensions…", installing: "Installation…" },
  updates: { available: "MemoryLane {{version}} est disponible.", downloading: "Téléchargement sécurisé…", restart: "Redémarrez pour terminer la mise à jour.", install: "Redémarrer et installer", starting: "Démarrage…", dismiss: "Ignorer la mise à jour {{version}}" },
  onboardingRuntime: { starting: "Démarrage de {{name}}…", installFailed: "Échec de l’installation de l’extension" },
  applePhotos: { imageNotLocal: "Image non disponible localement", checkLocal: "Rechercher une copie locale", title: "Photos Apple", devicePhotos: "Photos de l’appareil Apple", unavailablePlatform: "Indisponible sur cette plateforme", readOnly: "Importation en lecture seule depuis une photothèque Photos locale de macOS.", notSynced: "Non synchronisée", preparing: "Préparation du catalogue Photos{{elapsed}}", elapsed: " · {{seconds}} s écoulées", syncSummary: "{{processed}} / {{total}} · {{status}}", skipped: " · {{count}} ignorés", service: "Service de l’extension : {{status}}. MemoryLane le démarre et le surveille automatiquement.", checking: "Vérification…", permissionHint: "Si la photothèque est illisible, accordez l’Accès complet au disque à MemoryLane dans Réglages Système, puis réessayez.", path: "Chemin de la photothèque", addLibrary: "Ajouter la photothèque", detected: "Détectée : {{path}}", usePath: "Utiliser ce chemin", fullDiskAccess: "MemoryLane a besoin de l’Accès complet au disque pour lire cette photothèque. Ouvrez Réglages Système → Confidentialité et sécurité → Accès complet au disque, activez MemoryLane, puis quittez et relancez entièrement MemoryLane.", noLibraries: "Aucune photothèque ajoutée.", indexed: "{{count}} indexés · {{summary}}", availability: "{{previewOnly}} avec aperçu uniquement · {{unavailable}} indisponibles", previousError: "Erreur de synchronisation précédente : {{error}}", syncNow: "Synchroniser" },
  appleBrowse: { loadFailed: "Impossible de charger Photos Apple", openFailed: "Impossible d’ouvrir Photos", noLocal: "Aucune image locale utilisable. Affichez la photo dans Photos, puis réessayez.", checkFailed: "Impossible de vérifier la copie locale", moreFailed: "Impossible de charger davantage de photos", markTitle: "Marquer {{count}} élément de Photos Apple ?", markTitle_other: "Marquer {{count}} éléments de Photos Apple ?", markMessage: "Ils disparaîtront de la navigation MemoryLane et resteront dans Nettoyage. Aucun fichier de la photothèque ne sera modifié.", mark: "Marquer pour suppression", markFailed: "Impossible de marquer les éléments Photos Apple", breadcrumbs: "Fil d’Ariane Photos Apple", allPhotos: "Toutes les photos", unknownDate: "Date inconnue", items: "{{count}} élément", items_other: "{{count}} éléments", select: "Sélectionner", selected: "{{count}} sélectionnés", selectShown: "Sélectionner les {{count}} affichés", none: "Aucun", invert: "Inverser l’affichage", loadMore: "Charger plus", loading: "Chargement de Photos Apple…" },
  appleErrors: { notRunning: "à l’arrêt", addFailed: "Impossible d’ajouter la photothèque", syncFailed: "Impossible de démarrer la synchronisation" },
  settingsUi: {
    theme: { light: "Clair", dark: "Sombre", dusk: "Crépuscule", gallery: "Galerie" }, passwordMismatch: "Les nouveaux mots de passe ne correspondent pas", passwordFailed: "Impossible de modifier le mot de passe", newPasswordHint: "Nouveau mot de passe (8 caractères min.)", confirmNewPassword: "Confirmer le nouveau mot de passe", passwordChanged: "Mot de passe modifié. Vous restez connecté ici ; les autres appareils ont été déconnectés.", changing: "Modification…",
    moveTitle: "Déplacer les données de MemoryLane ?", moveMessageBefore: "Tout (base de données, miniatures, aperçus, vecteurs et visages) est maintenant copié vers", moveMessageAfter: "— environ une minute par Go, tandis que MemoryLane continue de fonctionner. Redémarrez ensuite l’application pour utiliser le nouvel emplacement ; l’ancienne copie reste jusqu’à sa suppression.", copyData: "Copier les données", moveFailed: "Échec du déplacement", recomputed: "Piles recalculées dans {{count}} dossier.", recomputed_other: "Piles recalculées dans {{count}} dossiers.", storageFailed: "Impossible de charger l’utilisation du stockage",
    scanFoldersHelp: "Ajoutez les dossiers contenant vos photos et vidéos. MemoryLane ne modifie, ne renomme et ne déplace jamais les originaux.", ignoredHelp: "Dossiers ignorés par MemoryLane à chaque analyse. Cliquez sur « Ignorer le dossier » pendant la navigation pour l’ajouter ici. Le retirer de cette liste ne restaure rien ; il sera repris lors de la prochaine analyse.", noIgnored: "Aucun dossier ignoré.", scanEvery: "Analyser automatiquement tous les", days: "jours", scanRunning: "Analyse en cours…", runAll: "Analyser maintenant (tous les dossiers)", startingScan: "Démarrage de l’analyse…", lastScan: "Dernière analyse : {{date}} — {{status}} — {{scanned}} analysés, {{newCount}} nouveaux, {{changed}} modifiés, {{removed}} retirés, {{errors}} erreurs.", lastSuccessful: "Dernière analyse réussie : {{date}}"
  },
  settingsAnalysis: {
    ai: "IA", aiIntroBefore: "Un service local facultatif (", aiIntroAfter: ") transforme les photos en vecteurs pour la recherche de similaires, la recherche descriptive, les piles intelligentes et les étiquettes IA. Rien ne quitte votre ordinateur.", analyseAi: "Analyser les photos avec le service IA lorsqu’il fonctionne", noProvider: "Aucun fournisseur IA configuré (MEMORYLANE_AI_PROVIDER=none).", connected: "Connecté à", notConnected: "Non connecté à", startBefore: "Démarrez-le avec", startAfter: "dans un second terminal (voir son README). Les photos restent en attente puis sont analysées lorsqu’il devient accessible ; cette carte s’actualise en quelques secondes.", backgroundHelp: "Traitement en arrière-plan après les analyses : capture EXIF, mots-clés, piles et, lorsque le service IA fonctionne, vecteurs, étiquettes et visages. Il se met automatiquement en pause pendant une analyse.", retryFailed: "Réessayer les échecs",
    peopleHelp: "Détecte les visages et les regroupe en personnes que vous pouvez nommer pour parcourir leurs photos. Désactivé par défaut car les visages sont des données personnelles ; tout est calculé et stocké uniquement sur cet ordinateur et peut être supprimé en un clic.", findFaces: "Détecter et regrouper les visages (service IA requis)", faceModel: "Modèle facial", switchTitle: "Changer de modèle facial ?", switchMessage: "Chaque photo sera réanalysée avec le nouveau modèle ; quelques minutes par plusieurs milliers de photos et un téléchargement initial. Les noms et visages confirmés ou rejetés sont conservés. Appuyez sur Regrouper à la fin.", switchModel: "Changer de modèle", standardModel: "Standard — YuNet + SFace (licence ouverte)", arcfaceModel: "ArcFace — InsightFace buffalo_l (plus précis, usage personnel uniquement)", arcfaceHelp: "ArcFace distingue bien mieux les visages similaires, prend environ 60 % de temps supplémentaire par photo, nécessite un téléchargement initial de 190 Mo et ses poids sont réservés à un usage non commercial.", modelUnavailable: "Le service actif ne propose pas ce modèle ; mettez-le à jour et redémarrez-le (npm run ai).", advancedPeople: "Paramètres avancés de Personnes", peopleAdvancedHelp: "Si une personne regroupe plusieurs personnes ressemblantes, augmentez les deux seuils (0,55–0,6 est un bon départ) puis appuyez sur Regrouper. Des réglages plus stricts créent davantage de petits groupes faciles à fusionner.", matchStrictness: "Seuil de correspondance (similarité min., 0,3–0,9)", facesNeeded: "Visages nécessaires pour créer une personne (2–20)", groupStrictness: "Seuil de regroupement (0,3–0,9)", regroupTitleHelp: "Regrouper tous les visages automatiques avec les paramètres actuels. Les noms et réponses sont conservés.", regroupTitle: "Regrouper les visages ?", regroupMessage: "Les regroupements automatiques seront refaits avec les seuils actuels. Les noms et visages confirmés ou rejetés sont conservés.", regroup: "Regrouper", regrouped: "Regroupés", regroupedMessage: "{{count}} nouvelle personne, {{assigned}} visages attribués.", regroupedMessage_other: "{{count}} nouvelles personnes, {{assigned}} visages attribués.", regroupSettings: "Regrouper avec ces paramètres", deleteTitle: "Supprimer toutes les données faciales ?", deleteMessage: "Les personnes, visages et vecteurs associés sont supprimés. Vos photos restent intactes. Les visages ne sont redétectés que lorsque Personnes est activé.", deleteFaceData: "Supprimer les données faciales", deleteAll: "Supprimer toutes les données faciales",
    stacksHelp: "Les rafales et séries sur trépied presque identiques sont regroupées en un élément. Les piles que vous modifiez ne sont jamais regroupées automatiquement.", advancedStacks: "Paramètres avancés des piles", burstGap: "Intervalle de rafale (secondes)", visualSimilarity: "Similarité visuelle (distance de hachage max., 0–64)", aiSimilarity: "Similarité IA (cosinus min., 0,5–1)", tripodGap: "Intervalle de série sur trépied (secondes)", recompute: "Recalculer toutes les piles"
  },
  settingsStorage: { calculating: "Calcul…", intro: "Le cache et l’index propres à MemoryLane sont entièrement séparés de vos dossiers photo ; vous pouvez les supprimer et les reconstruire par une nouvelle analyse à tout moment.", location: "Emplacement", sourceEnv: "Défini par MEMORYLANE_DATA_DIR dans l’environnement.", sourcePointer: "Choisi dans les Paramètres (l’emplacement par défaut contient un pointeur vers celui-ci).", sourceDefault: "Emplacement par défaut du système.", pendingBefore: "Les données ont été copiées vers", pendingAfter: "Redémarrez MemoryLane pour les utiliser ; la copie présente ici pourra ensuite être supprimée.", previews: "Aperçus (RAW plein écran)", thumbnails: "Cache des miniatures", database: "Base de données (index, EXIF, vecteurs)", vectors: "Index vectoriel", faces: "Découpes de visages", logs: "Journaux", total: "Total", moveHelp: "Déplacer vers un autre disque (un dossier vide, p. ex.", or: "ou", pathPlaceholder: "/chemin/absolu/vers/dossier/vide", copying: "Copie…", moveHere: "Déplacer les données ici", copied: "{{bytes}} copiés vers", restart: "Redémarrez MemoryLane", switchThenDelete: "pour basculer ; supprimez ensuite", freeSpace: "pour libérer l’espace.", useRefresh: "Utilisez Actualiser pour calculer l’espace utilisé." },
  settingsAbout: { tagline: "Une lettre d’amour à l’art de la photographie.", free: "Gratuit, sous licence MIT", authors: "Auteurs originaux :", licenses: "Autres licences et attributions", openSource: "MemoryLane est construit avec des logiciels libres. Les principaux composants sont :", licenseMit: "React, React DOM, React Router, Fastify, better-sqlite3, Argon2, Zod, Nano ID, bmp-js, open et p-limit — Licence MIT.", licenseLucide: "Lucide — Licence ISC.", licenseDotenv: "dotenv — Licence BSD à 2 clauses.", licenseSharp: "Sharp et sa distribution libvips — Licences Apache 2.0 et LGPL v3 ou ultérieure, respectivement.", licenseExif: "ExifTool et exiftool-vendored — ExifTool utilise la licence Artistic de Perl ou GNU GPL ; son enveloppe Node est sous licence MIT.", licenseFfmpeg: "FFmpeg — inclus via ffmpeg-static sous GNU GPL v3 ou ultérieure. FFprobe conserve sa licence FFmpeg applicable et l’enveloppe est sous licence MIT.", licenseTray: "Go systray et ses bibliothèques Go alimentent l’application de barre d’état sous leurs licences libres respectives.", plugins: "Les extensions facultatives peuvent inclure des bibliothèques, modèles et conditions supplémentaires. Leurs avis de licence sont distribués avec chaque extension.", copyright: "Les avis de droit d’auteur et de licence des dépendances restent la propriété de leurs auteurs et contributeurs. Les textes complets sont inclus avec le logiciel distribué lorsque nécessaire." },
  coreBrowse: {
    home: { titleError: "Impossible d’enregistrer le titre. Réessayez.", media: "{{count}} élément", media_other: "{{count}} éléments", folders: "{{count}} dossier", folders_other: "{{count}} dossiers", years: "{{count}} an", years_other: "{{count}} ans", random: "Souvenir aléatoire", onThisDay: "Ce jour-là, autrefois", archive: "Archives photographiques", archiveTitle: "Titre des archives", titlePlaceholder: "Albums de Jean", saving: "Enregistrement…", editTitle: "Modifier le titre des archives", edit: "Modifier", tier: { day: "Photos prises ce jour-là au fil des années.", week: "Aucune photo de ce jour exact ; voici la même semaine au fil des années.", month: "Rien pour cette semaine ; voici le même mois au fil des années." }, noDated: "Aucune photo datée pour retrouver des souvenirs ; les dates proviennent des métadonnées.", noFolders: "Aucun dossier photo configuré. Ouvrez les Paramètres pour ajouter un dossier." },
    folder: { stackFailed: "Impossible de créer la pile", markTitle: "Marquer {{count}} élément pour suppression ?", markTitle_other: "Marquer {{count}} éléments pour suppression ?", markMessage: "Ils quitteront la navigation normale et apparaîtront dans Nettoyage. Vous pourrez les y restaurer. Aucun fichier ne sera encore déplacé.", mark: "Marquer pour suppression", markFailed: "Impossible de marquer les éléments", indexedItems: " et {{count}} élément indexé qu’il contient", indexedItems_other: " et {{count}} éléments indexés qu’il contient", ignoreTitle: "Ignorer « {{name}} » ?", ignoreMessage: "MemoryLane cessera d’analyser ce dossier{{items}}, qui sera retiré de votre bibliothèque. Les fichiers originaux ne sont jamais modifiés ; vous pourrez le retirer de la liste d’exclusion et relancer une analyse.", ignore: "Ignorer le dossier", selected: "sélectionnés", selectShownTitle: "Sélectionner les {{count}} éléments affichés", allShown: "Tous les éléments affichés", clear: "Effacer", invert: "Inverser", marking: "Marquage…", stackSelected: "Empiler la sélection", done: "Terminé", selectHelp: "Sélectionner des photos à nettoyer ou empiler", select: "Sélectionner", allFiles: "Tous les fichiers", more: "Plus d’options", ignoring: "Exclusion…", empty: "Ce dossier est vide.", noPhotos: "Aucune photo dans ce dossier.", noVideos: "Aucune vidéo dans ce dossier.", noFilesRecursive: "Aucun fichier dans ce dossier ni ses sous-dossiers.", noPhotosRecursive: "Aucune photo dans ce dossier ni ses sous-dossiers.", noVideosRecursive: "Aucune vidéo dans ce dossier ni ses sous-dossiers.", loadingMore: "Chargement supplémentaire ({{current}} / {{total}})…" },
    cleanup: { loadFailed: "Impossible de charger Nettoyage", moreFailed: "Impossible de charger davantage", restoreItemFailed: "Impossible de restaurer l’élément", moveTitle: "Déplacer {{count}} élément vers la corbeille ?", moveTitle_other: "Déplacer {{count}} éléments vers la corbeille ?", moveMessage: "Cette action déplacera {{size}} de fichiers originaux, y compris les fichiers RAW associés, Live Photo et annexes, vers des dossiers _MemoryLane-Trash visibles. Vous pourrez les restaurer depuis Nettoyage.", moveTrash: "Déplacer vers la corbeille", moveFailures: "{{count}} élément n’a pas pu être déplacé : {{error}}", moveFailures_other: "{{count}} éléments n’ont pas pu être déplacés : {{error}}", unknownError: "Erreur inconnue", moveFailed: "Impossible de déplacer les fichiers", restoreFileFailed: "Impossible de restaurer le fichier", deleteTitle: "Supprimer définitivement {{filename}} ?", deleteMessage: "Cette action supprimera définitivement les fichiers de _MemoryLane-Trash pour cet élément. {{size}} ou plus peuvent être supprimés, y compris les fichiers associés. Cette action est irréversible dans MemoryLane.", deletePermanently: "Supprimer définitivement", deleteFailed: "Impossible de supprimer le fichier", summary: "{{count}} élément marqué et masqué de la navigation. Les fichiers déplacés dans la corbeille MemoryLane peuvent être restaurés ici.", summary_other: "{{count}} éléments marqués et masqués de la navigation. Les fichiers déplacés dans la corbeille MemoryLane peuvent être restaurés ici.", selectShown: "Sélectionner tous les éléments affichés", moveSelected: "Déplacer {{count}} éléments sélectionnés", emptyTitle: "Aucun élément marqué pour nettoyage", emptyHelp: "Ouvrez un dossier, choisissez Sélectionner, sélectionnez des photos, puis choisissez Marquer pour suppression. Le marquage les masque seulement ; aucun fichier n’est déplacé avant votre vérification ici.", browse: "Parcourir votre bibliothèque", previewUnavailable: "Aperçu indisponible", marked: "{{size}} · Marqué le {{date}}", inTrash: "Dans la corbeille MemoryLane", interrupted: "Déplacement interrompu — restaurez les fichiers", originalUnavailable: "Original actuellement indisponible", selectTrash: "Sélectionner pour la corbeille", restoreLibrary: "Restaurer dans la bibliothèque", restoreFiles: "Restaurer les fichiers" }
  },
  reportsUi: { lens: "Objectif", camera: "Appareil", make: "Marque", aperture: "Ouverture", iso: "ISO", focal: "Distance focale", year: "Année", exifMatch: "{{count}} photo avec données EXIF correspond", exifMatch_other: "{{count}} photos avec données EXIF correspondent", analysisProgress: "Voir la progression de l’analyse", exploreMuseum: "Explorer le Musée du matériel", exploreTimeline: "Explorer la chronologie du matériel", export: "Exporter en CSV", from: "Du", to: "Au", clearAll: "Tout effacer", moreFilters: "Plus de filtres", loadingPhotos: "Chargement des photos…", noMatch: "Aucune photo correspondante. Les données EXIF sont capturées pendant les analyses ; si la bibliothèque a été indexée auparavant, le traitement dans Paramètres → Analyse les complète.", loadingMore: "Chargement supplémentaire ({{current}} / {{total}})…" },
  gearUi: { museumIntro: "Une collection des appareils qui ont capturé votre bibliothèque.", timelineIntro: "L’histoire de vos appareils, présentée chronologiquement.", searchLenses: "Rechercher des objectifs…", searchCameras: "Rechercher des appareils…", noExif: "Aucune donnée EXIF d’appareil dans votre bibliothèque.", cameras: "{{count}} appareil", cameras_other: "{{count}} appareils", lenses: "{{count}} objectif", lenses_other: "{{count}} objectifs", timelineType: "Type de matériel de la chronologie", cameraPlural: "Appareils", lensPlural: "Objectifs", minPhotos: "Photos min.", refresh: "Actualiser depuis le service du musée", sort: "Trier : {{value}}", sorts: { photos: "Plus de photos", recent: "Utilisés récemment", name: "Nom" }, noTimeline: "Aucune photo datée pour créer une chronologie.", yearTitle: "{{name}} — {{year}} : {{count}} photos ({{percent}} % des photos de cette année)", memories: "{{count}} souvenir capturé", memories_other: "{{count}} souvenirs capturés", viewReports: "Voir toutes les photos dans Rapports", firstUsed: "Première utilisation", lastUsed: "Dernière utilisation", mostLens: "Objectif le plus utilisé", places: "Lieux photographiés", photosByYear: "Photos par année", hideDetails: "Masquer les détails techniques", showDetails: "Afficher les détails techniques", brand: "Marque", released: "Sortie", weight: "Poids", size: "Dimensions", isoRange: "Plage ISO", apertureRange: "Plage d’ouverture", noSpecs: "Aucune spécification trouvée pour cet appareil.", lensesUsed: "Objectifs utilisés avec cet appareil", allLenses: "Tous les objectifs", photosFrom: "Photos de cet appareil", inYear: "en {{year}}", allYears: "Afficher toutes les années", viewAll: "Tout afficher ({{count}})" },
  onboardingAction: { startingScan: "Démarrage de l’analyse…" },
} as const;
