// Generates src/version.ts as a plain compiled-in string constant, rather
// than reading package.json at runtime - a runtime path lookup here would
// repeat the exact class of bug migrate.ts had (server/migrations resolution
// breaking once the compiled server ships somewhere that doesn't mirror the
// dev source tree's layout, like the desktop app's runtime/ folder, which
// doesn't carry a copy of server/package.json at all). A build-time constant
// sidesteps deployment-layout differences entirely.
import fs from "node:fs";
import path from "node:path";

const serverRoot = path.join(import.meta.dirname, "..");
const pkg = JSON.parse(fs.readFileSync(path.join(serverRoot, "package.json"), "utf8"));

const content = `// Generated by scripts/generate-version.mjs at build time from package.json - do not edit directly.
export const APP_VERSION = ${JSON.stringify(pkg.version)};
`;

fs.writeFileSync(path.join(serverRoot, "src", "version.ts"), content);
console.log(`Generated src/version.ts (${pkg.version})`);
